defaultSize: 5

graphql:
  enableTracing: false
  queryCache: maximumSize=10000
  schemaFiles:
    - dropwizard.graphql

# HTTP-specific options.
server:
  type: simple
  rootPath: /api/
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8082

  requestLog:
    appenders:
      - type: console
        timeZone: UTC
        target: stdout

database:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/TESTS
  user: root
  password: Qwerty12345%$#@!
  validationQuery: "SELECT 1"