defaultSize: 5
server:
  applicationConnectors:
    - type: http
      port: 8082
database:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/TESTS
  user: root
  password: Qwerty12345%$#@!
  validationQuery: "SELECT 1"